In [ ]:
#cross-correlation:

import numpy as np
import matplotlib.pyplot as plt

def cor(x,h):
    lx = len(x)
    lh = len(h)
    y = np.zeros((lx+lh-1))

    for m in range(lx):
       for n in range(lh): 
            y[m+n] = y[m+n] + x[m]*h[n]
    return y
x = [1,2,3,1]
h = [1,2,1,-1]

y = cor(x,np.flip(h))
print(y)

[-1. -1.  1.  7.  9.  5.  1.]


In [ ]:
z = np.correlate(x,h, 'full')
print(z)

[-1 -1  1  7  9  5  1]


In [ ]:
def crosscorr(x,h):
    lx = len(x)
    h = np.flip(h)
    lh = len(h)
    y = np.zeros((lx+lh-1))

    for m in range(lx):
       for n in range(lh): 
            y[m+n] = y[m+n] + x[m]*h[n]
    return y
x = [1,2,3,1]
y = [1,2,1,-1]

rxy = crosscorr(x,y)
print(rxy)

z = np.correlate(x,y, 'full')
print(z)

[-1. -1.  1.  7.  9.  5.  1.]
[-1 -1  1  7  9  5  1]


In [ ]:
#auto-correlation:

import numpy as np
import matplotlib.pyplot as plt

def conv(x,h):
    lx = len(x)
    lh = len(h)
    y = np.zeros((lx+lh-1))

    for m in range(lx):
       for n in range(lh): 
            y[m+n] = y[m+n] + x[m]*h[n]
    return y
x = [1,2,3,1]
h = [1,2,1,-1]

y = conv(x,np.flip(x))
print(y)

[ 1.  5. 11. 15. 11.  5.  1.]


In [ ]:
z = np.correlate(x,x, 'full')
print(z)

[ 1  5 11 15 11  5  1]
