In [ ]:
#convolve Sum:

import numpy as np
import matplotlib.pyplot as plt
x = [1,2,3,1]
h = [1,2,1,-1]
lx = len(x)
lh = len(h)
y = np.zeros((lx+lh-1))

for m in range(lx):
   for n in range(lh): 
        y[m+n] = y[m+n] + x[m]*h[n]
print(y)

[ 1.  4.  8.  8.  3. -2. -1.]


In [ ]:
z = np.convolve(x,h, 'full')
print(z)

[ 1  4  8  8  3 -2 -1]


In [ ]:
#convolve Sum using function:

def conv(x,h):
    lx = len(x)
    lh = len(h)
    y = np.zeros((lx+lh-1))

    for m in range(lx):
       for n in range(lh): 
            y[m+n] = y[m+n] + x[m]*h[n]
    return y
x = [1,2,3,1]
h = [1,2,1,-1]

y = conv(x,h)
print(y)

[ 1.  4.  8.  8.  3. -2. -1.]
