In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def conv(x,h):
    lx = len(x)
    lh = len(h)
    y = np.zeros((lx+lh-1))

    for m in range(lx):
       for n in range(lh): 
            y[m+n] = y[m+n] + x[m]*h[n]
    return y

x=[1,2,3,1]
h=[1,2,1,-1]
y= conv(x,h)
print(y)

d= np.zeros(1)
d[0]=1

# Identity law:
yi=conv(x,d)
print(yi)

# Commutative law:
yc= conv(h,x)
print(yc)

# Associative law:
h2=[1,2,1,2]
yd3= conv(h,h2)
ya= conv(yc,h2)
print(ya)

ya2= conv(y,yd3)
print(ya2)

# Distributive law:
yd= conv(y,h2)
print(yd)

yd3= conv(h,h2)
yd2= conv(x,yd3)
print(yd2)

[ 1.  4.  8.  8.  3. -2. -1.]
[1. 2. 3. 1.]
[ 1.  4.  8.  8.  3. -2. -1.]
[ 1.  6. 17. 30. 35. 28. 14.  2. -5. -2.]
[  1.   8.  30.  69. 106. 111.  75.  23. -15. -24. -11.   3.   2.]
[ 1.  6. 17. 30. 35. 28. 14.  2. -5. -2.]
[ 1.  6. 17. 30. 35. 28. 14.  2. -5. -2.]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def conv(x,h):
    lx = len(x)
    lh = len(h)
    y = np.zeros((lx+lh-1))

    for m in range(lx):
       for n in range(lh): 
            y[m+n] = y[m+n] + x[m]*h[n]
    return y

x=[1,2,3,1]
h=[1,2,1,-1]
y= conv(x,h)
print(y)

d= np.zeros(1)
d[0]=1

# Identity law:
yi=conv(x,d)
print(yi)

# Commutative law:
yc= conv(h,x)
print(yc)

# Associative law:
h2=[1,2,1,2]
ya= conv(yc,h2)
print(ya)

ya2= conv(h2,yc)
print(ya2)

# Distributive law:
yd= conv(y,h2)
print(yd)

yd3= conv(h,h2)
yd2= conv(x,yd3)
print(yd2)

[ 1.  4.  8.  8.  3. -2. -1.]
[1. 2. 3. 1.]
[ 1.  4.  8.  8.  3. -2. -1.]
[ 1.  6. 17. 30. 35. 28. 14.  2. -5. -2.]
[ 1.  6. 17. 30. 35. 28. 14.  2. -5. -2.]
[ 1.  6. 17. 30. 35. 28. 14.  2. -5. -2.]
[ 1.  6. 17. 30. 35. 28. 14.  2. -5. -2.]
